apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
data:
  spring.profiles.active: "kubernetes"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_LUNAIRE: "DEBUG"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"

